### ISSUE TITLE
seed.yml missing

### ISSUE THREAD

**Issue by tj** [jfd/optparse-js#1]
Not sure what happened but the latest version on kiwi does not have seed.yml
      λ  jspec: kiwi install optparse
   install : optparse
   resolve : version 1.0.1
    create : /Users/tjholowaychuk/.kiwi/current/seeds/optparse/1.0.1
     fetch : 1.0.1.seed
    unpack : /Users/tjholowaychuk/.kiwi/current/seeds/optparse/1.0.1/optparse.seed
    remove : /Users/tjholowaychuk/.kiwi/current/seeds/optparse/1.0.1/optparse.seed
Error: seed.yml file required.

**Comment by jfd** [comment]
Should be fixed now. Please uninstall and install again.

**Comment by tj** [comment]
worken now, thanks!
