### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by toabi** [jfd/optparse-js#7]
Hubot (https://github.com/github/hubot) doesn't run on Debian with node 0.4.12 because the currently released version of this module doesn't work there. One has to manually pull the optparse code, and then it runs.

It would be great to see a new release with the latest fixes.

See also: https://github.com/github/hubot/issues/132

**Comment by mexitek** [comment]
I too would like a new version with bug fixes released on NPM. thanks.

**Comment by stuartf** [comment]
+1

**Comment by jfd** [comment]
Up n running 

http://search.npmjs.org/#/optparse
